language: c
os: linux
dist: bionic
services:
  - docker
env:
  global:
    - ci_env=`bash <(curl -s https://codecov.io/env)`
    - COVERITY_SCAN_PROJECT_NAME="jluebbe/rauc"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="jlu@pengutronix.de"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND="cov-configure --comptype gcc --compiler gcc-8 --template && ./autogen.sh && ./configure --enable-gpt CC=gcc-8"
    - COVERITY_SCAN_BUILD_COMMAND="make V=1"

stages:
  - name: Main Build and Tests
  - name: Cross-Builds
  - name: Static Analysis

jobs:
  include:
    - stage: Main Build and Tests
      before_script:
        - docker pull rauc/testing:latest
        # Create container and export env variables for Coverity scan
        - cat /proc/cpuinfo
        - sudo chmod 666 /dev/kvm
        - ls -l /dev/kvm
        - |
            docker run -dit --privileged \
            -v "$PWD":/home/travis -w /home/travis \
            --tmpfs /tmp/qemu:exec,mode=777 \
            --tmpfs /tmp:exec \
            -v ${TOOL_BASE}:${TOOL_BASE} \
            -u travis $ci_env \
            --name rauc-ci rauc/testing:latest bash
        - docker exec -it rauc-ci gcc --version

      script:
        - docker exec -it rauc-ci ./autogen.sh
        - docker exec -it rauc-ci ./configure --enable-code-coverage --enable-gpt CFLAGS=-Werror
        - docker exec -it rauc-ci make clean
        - docker exec -it rauc-ci make -j2
        - docker exec -it rauc-ci make doc SPHINXOPTS=-W
        - docker exec -it rauc-ci make check TESTS=
        - docker exec -it rauc-ci ./qemu-test
        - docker exec -it rauc-ci lcov --directory . --capture --output-file "service.info"
        - docker exec -it rauc-ci ./configure --enable-code-coverage --disable-service CFLAGS=-Werror
        - docker exec -it rauc-ci make clean
        - docker exec -it rauc-ci make -j2
        - docker exec -it rauc-ci make check TESTS=
        - docker exec -it rauc-ci ./qemu-test
        - docker exec -it rauc-ci lcov --directory . --capture --output-file "noservice.info"
        - docker exec -it rauc-ci make distcheck
        - docker exec -it rauc-ci /bin/sh -c 'cd /home/travis/contrib/cgi && ./autogen.sh && ./configure CFLAGS=-Werror && make clean && make -j2 && make distcheck'
        - ./uncrustify.sh && git diff --exit-code
      after_success:
        - docker exec -it rauc-ci /usr/bin/codecov -f service.info -f noservice.info
      after_failure:
        - cat test/*.log || true
        - cat test-suite.log || true
        - cat rauc-*/_build/sub/test-suite.log || true
    - &cross
      stage: Cross-Builds
      name: armhf
      before_install:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      install:
        - docker run --name cross -dit -v "$PWD":/home -w /home multiarch/debian-debootstrap:armhf-buster bash
      before_script:
        - docker exec -it cross uname -a
        - docker exec -it cross apt-get update
        - docker exec -it cross apt-get install -y build-essential automake libtool libglib2.0-dev libcurl3-dev libssl-dev libjson-glib-dev libdbus-1-dev libfdisk-dev
      script:
        - docker exec -it cross ./autogen.sh
        - docker exec -it cross ./configure --enable-gpt CFLAGS=-Werror
        - docker exec -it cross make
      after_script:
        - docker stop cross
      after_failure:
        - cat config.log || true
        - cat test/*.log || true
        - cat test-suite.log || true
        - cat rauc-*/_build/sub/test-suite.log || true
    - <<: *cross
      name: arm64
      install:
        - docker run --name cross -dit -v "$PWD":/home -w /home multiarch/debian-debootstrap:arm64-buster bash
    - <<: *cross
      name: i386
      install:
        - docker run --name cross -dit -v "$PWD":/home -w /home multiarch/debian-debootstrap:i386-buster bash
    - <<: *cross
      name: armel
      install:
        - docker run --name cross -dit -v "$PWD":/home -w /home multiarch/debian-debootstrap:armel-buster bash
    - stage: Static Analysis
      if: |
        env(COVERITY_SCAN_TOKEN) IS present AND
        branch IN (master, coverity) AND
        type NOT IN (pull_request)
      before_script:
        - docker pull rauc/testing:latest
      script:
        # Prepare environment for Coverity tool
        - |
            PLATFORM=`uname`
            export TOOL_BASE="/tmp/coverity-scan-analysis"
            export SCAN_URL="https://scan.coverity.com"
            export UPLOAD_URL="https://scan.coverity.com/builds"
            export TOOL_ARCHIVE="/tmp/cov-analysis-${PLATFORM}.tgz"

        # Get Coverity tool
        - test/get-coverity.sh
        - TOOL_DIR="$(find $TOOL_BASE -type d -name 'cov-analysis*' || exit 0)"

        # Create container and export env variables for Coverity scan
        - env | grep -E "TRAVIS|COV|TOOL|URL" > .cov-env
        - |
            docker run -dit --privileged \
            --env-file .cov-env \
            -v "$PWD":/home/travis -w /home/travis \
            --tmpfs /tmp:exec \
            -v ${TOOL_BASE}:${TOOL_BASE} \
            -u travis $ci_env \
            --name rauc-ci rauc/testing:latest bash
        - docker exec -it rauc-ci gcc --version

        # Make sure Coverity script is executable
        - docker cp test/run-coverity.sh rauc-ci:/usr/local/bin

        # Run Coverity Analysis
        - docker exec -it rauc-ci run-coverity.sh build
        - docker exec -it rauc-ci run-coverity.sh upload
