language: c
sudo: required
compiler: gcc-6
dist: trusty
before_install:
  - sudo pip install --upgrade cpp-coveralls
addons:
  apt:
    packages:
      - autoconf
      - automake
      - libglib2.0-dev
      - libjson-glib-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - squashfs-tools
      - dosfstools
      - lcov
      - slirp
      - python-sphinx
      - dbus-x11
      - gcc-6
      - user-mode-linux
      - grub-common
    sources: &sources
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse'
  coverity_scan:
    project:
      name: "jluebbe/rauc"
      description: "Robust Auto-Update Controller"
    notification_email: jluebbe@lasnet.de
    build_command_prepend: "cov-configure --comptype gcc --compiler gcc-6 --template && ./autogen.sh && ./configure"
    build_command: "make -j2"
    branch_pattern: master
script:
  - ./autogen.sh
  - ./configure --enable-code-coverage
  - make clean
  - make -j2
  - make doc SPHINXOPTS=-W
  - make check TESTS= && sudo ./uml-test
  - make distcheck
after_success:
  - coveralls --build-root '.' --exclude test --exclude rauc-installer-generated.c
after_failure:
  - cat test/*.log
