#!/bin/bash

echo "[OK]"

echo "SYSTEM_CONFIG: $SYSTEM_CONFIG"
echo "CURRENT_BOOTNAME: $CURRENT_BOOTNAME"
echo "TARGET_SLOTS: $TARGET_SLOTS"
echo "UPDATE_SOURCE: $UPDATE_SOURCE"
echo "MOUNT_PREFIX: $MOUNT_PREFIX"

exit 0
