name: scan-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
      options: --user=root
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        DEBIAN_FRONTEND='noninteractive' apt-get install -qy meson libtool libglib2.0-dev libcurl3-dev libssl-dev libdbus-1-dev libjson-glib-dev libfdisk-dev libnl-genl-3-dev dbus-x11 clang-tools

    - name: Inspect environment
      run: |
        whoami
        gcc --version
        ls -la /usr/bin/clang*

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Run meson
      run: |
        meson setup build

    - name: Run scan-build
      run: |
        SCANBUILD=$(pwd)/scan-build-wrapper.sh ninja -C build scan-build

    - name: Upload scan-build report
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: scan-build-report
        path: build/meson-logs/scanbuild/*
